name: hello-world
on: push
jobs:
  my-job:
    runs-on: windows-2019
    steps:
      - name: Install pgvector
        run: |
          "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat"
          set "PGROOT=C:\Program Files\PostgreSQL\14"
          cd $env:RUNNER_TEMP
          git clone --branch v0.6.2 https://github.com/pgvector/pgvector.git
          cd pgvector
          nmake /F Makefile.win
          nmake /F Makefile.win install
